### ISSUE TITLE
Maven Central?

### ISSUE THREAD

**Issue by egonw** [dan2097/jna-inchi#7]
Is the module available from Maven Central? I do not seem to be able to find it. If not, can you please consider uploading it there?

**Comment by dan2097** [comment]
It's not there currently, mainly as the project isn't quite feature complete, specifically I don't think I've implemented the handling of wedge/hatch bond input (which aren't used when going from SMILES). I'll try and get motivated to finish it.
Ideally for the version 1.0 release I want binaries based on next InChI bug fix release, as well as binaries for mac as this would give provide feature parity with JNI-InChI. The next InChI bug fix should fix an issue with the IXA API which makes creating the input for InChI slower than it should be, although this is only really problematic on very large molecules. I'm hoping this will be sufficient to bring the speed approximately on a par with JNI-InChI

**Comment by dan2097** [comment]
Just to add the missing functionality I'm referring to doesn't effect the molToInchi method as that uses the InChI's built-in mol file reader; a project like the CDK which would want to convert directly from its internal representation would be effected.

**Comment by dan2097** [comment]
v1.0 is now on Maven Central

**Comment by egonw** [comment]
Oh, awesome!
